import { auth } from '../firebaseConfig';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { supabase } from '../config/supabase';

// Helper function to check if the user entered an email or phone number
const isEmail = (input: string) => input.includes('@');

// Register a new user on both Firebase and Supabase
export const registerUser = async (identifier: string, password: string) => {
  try {
      let userCredential;
          const isEmailInput = isEmail(identifier);

              // 1. Primary Action: Register the user with Firebase Auth
                  if (isEmailInput) {
                        userCredential = await createUserWithEmailAndPassword(auth, identifier, password);
                            } else {
                                  // For phone registration with a password, ensure the identifier format is E.164 (e.g., +1234567890)
                                        userCredential = await createUserWithEmailAndPassword(auth, `${identifier}@phone.local`, password);
                                            }
                                                const user = userCredential.user;

                                                    // 2. Secondary Action: Background sync to Supabase Auth
                                                        if (user) {
                                                              try {
                                                                      if (isEmailInput) {
                                                                                await supabase.auth.signUp({
                                                                                            email: identifier,
                                                                                                        password: password,
                                                                                                                    options: { data: { firebase_uid: user.uid } }
                                                                                                                              });
                                                                                                                                      } else {
                                                                                                                                                await supabase.auth.signUp({
                                                                                                                                                            phone: identifier,
                                                                                                                                                                        password: password,
                                                                                                                                                                                    options: { data: { firebase_uid: user.uid } }
                                                                                                                                                                                              });
                                                                                                                                                                                                      }
                                                                                                                                                                                                              console.log("Dual-Backend Success: User created in Supabase Auth.");
                                                                                                                                                                                                                    } catch (supabaseError: any) {
                                                                                                                                                                                                                            console.warn("Supabase background synchronization failed:", supabaseError.message);
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          return user;
                                                                                                                                                                                                                                            } catch (error: any) {
                                                                                                                                                                                                                                                throw new Error(error.message);
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                  // Login existing user into both backends
                                                                                                                                                                                                                                                  export const loginUser = async (identifier: string, password: string) => {
                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                        let userCredential;
                                                                                                                                                                                                                                                            const isEmailInput = isEmail(identifier);

                                                                                                                                                                                                                                                                // 1. Authenticate user via Firebase
                                                                                                                                                                                                                                                                    if (isEmailInput) {
                                                                                                                                                                                                                                                                          userCredential = await signInWithEmailAndPassword(auth, identifier, password);
                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                    userCredential = await signInWithEmailAndPassword(auth, `${identifier}@phone.local`, password);
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                // 2. Simultaneously log the user into Supabase in the background
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                          if (isEmailInput) {
                                                                                                                                                                                                                                                                                                                  await supabase.auth.signInWithPassword({
                                                                                                                                                                                                                                                                                                                            email: identifier,
                                                                                                                                                                                                                                                                                                                                      password: password,
                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                            await supabase.auth.signInWithPassword({
                                                                                                                                                                                                                                                                                                                                                                      phone: identifier,
                                                                                                                                                                                                                                                                                                                                                                                password: password,
                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                    console.log("Dual-Backend Success: User logged into Supabase Auth.");
                                                                                                                                                                                                                                                                                                                                                                                                        } catch (supabaseError: any) {
                                                                                                                                                                                                                                                                                                                                                                                                              console.warn("Supabase background login failed:", supabaseError.message);
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                      return userCredential.user;
                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Error(error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                              // Logout from both platforms
                                                                                                                                                                                                                                                                                                                                                                                                                              export const logoutUser = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                    // 1. Clear out the Firebase user session
                                                                                                                                                                                                                                                                                                                                                                                                                                        await signOut(auth);

                                                                                                                                                                                                                                                                                                                                                                                                                                            // 2. Instantly clear out the local Supabase user session cache
                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { error } = await supabase.auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (error) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("Dual-Backend Success: Session wiped from Supabase cache.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (supabaseError: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.warn("Supabase local logout processing error:", supabaseError.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      throw new Error(error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        