// src/services/encryption.ts
import CryptoJS from 'crypto-js';
import 'react-native-get-random-values'; // Essential helper for uuidv4 in React Native environments
import { v4 as uuidv4 } from 'uuid';
import { db } from '../firebaseConfig';
import { supabase } from '../config/supabase';
import { doc, setDoc } from 'firebase/firestore';

/**
 * Generate a unique secret key per chat
  * Typically store this key in Firestore per chat, NOT hardcoded
   */
   export const generateChatKey = (): string => {
     return uuidv4(); // returns a unique UUID to use as a secret key
     };

     /**
      * Persist the generated encryption key to both Firestore and Supabase simultaneously
       * @param chatId The unique ID of the chat room
        * @param secretKey The key generated by generateChatKey()
         */
         export const saveChatKeyToDatabases = async (chatId: string, secretKey: string): Promise<void> => {
           // 1. Save to Firebase Firestore (Parallel Logic)
             try {
                 await setDoc(
                       doc(db, 'chats', chatId),
                             { encryptionKey: secretKey },
                                   { merge: true }
                                       );
                                         } catch (fbError) {
                                             console.error('Failed to save encryption key to Firebase:', fbError);
                                               }

                                                 // 2. Save to Supabase Database (Parallel Logic)
                                                   try {
                                                       const { error } = await supabase
                                                             .from('chats')
                                                                   .upsert({ 
                                                                           id: chatId, 
                                                                                   encryption_key: secretKey 
                                                                                         });

                                                                                             if (error) {
                                                                                                   console.error('Supabase error saving encryption key:', error.message);
                                                                                                       }
                                                                                                         } catch (supaError) {
                                                                                                             console.error('Failed to save encryption key to Supabase:', supaError);
                                                                                                               }
                                                                                                               };

                                                                                                               /**
                                                                                                                * Encrypt a message with a specific key
                                                                                                                 * @param text message to encrypt
                                                                                                                  * @param secretKey unique key for this chat
                                                                                                                   */
                                                                                                                   export const encryptMessage = (text: string, secretKey: string): string => {
                                                                                                                     return CryptoJS.AES.encrypt(text, secretKey).toString();
                                                                                                                     };

                                                                                                                     /**
                                                                                                                      * Decrypt a message with a specific key
                                                                                                                       * @param ciphertext encrypted text
                                                                                                                        * @param secretKey unique key for this chat
                                                                                                                         */
                                                                                                                         export const decryptMessage = (ciphertext: string, secretKey: string): string => {
                                                                                                                           const bytes = CryptoJS.AES.decrypt(ciphertext, secretKey);
                                                                                                                             return bytes.toString(CryptoJS.enc.Utf8);
                                                                                                                             };
                                                                                                                             