// src/services/followService.ts
import { db } from '../firebaseConfig';
import {
  doc,
    setDoc,
      deleteDoc,
        getDoc,
          updateDoc,
            increment,
              serverTimestamp,
              } from 'firebase/firestore';
              import { createClient } from '@supabase/supabase-js';

              // Initialize or import your configured Supabase client
              // import { supabase } from '../supabaseConfig';
              const supabase = createClient('YOUR_SUPABASE_URL', 'YOUR_SUPABASE_ANON_KEY');

              /**
               * Async wrapper for sending Expo push notifications
                */
                const sendPushNotification = async (token: string, title: string, body: string) => {
                  try {
                      await fetch('https://exp.host', {
                            method: 'POST',
                                  headers: { 'Content-Type': 'application/json' },
                                        body: JSON.stringify({
                                                to: token,
                                                        sound: 'default',
                                                                title,
                                                                        body,
                                                                              }),
                                                                                  });
                                                                                    } catch (err) {
                                                                                        console.error('Error sending push notification:', err);
                                                                                          }
                                                                                          };

                                                                                          /**
                                                                                           * Checks if currentUserId is following targetUserId (Reads from Firebase primary)
                                                                                            */
                                                                                            export const checkIfFollowing = async (currentUserId: string, targetUserId: string): Promise<boolean> => {
                                                                                              try {
                                                                                                  const followSnap = await getDoc(
                                                                                                        doc(db, 'following', currentUserId, 'userFollowing', targetUserId)
                                                                                                            );
                                                                                                                return followSnap.exists();
                                                                                                                  } catch (error) {
                                                                                                                      console.error('Error checking follow status:', error);
                                                                                                                          return false;
                                                                                                                            }
                                                                                                                            };

                                                                                                                            /**
                                                                                                                             * FOLLOW USER (Dual Write to Firebase and Supabase)
                                                                                                                              */
                                                                                                                              export const followUser = async (currentUserId: string, targetUserId: string) => {
                                                                                                                                if (currentUserId === targetUserId) return;

                                                                                                                                  try {
                                                                                                                                      // 1. Get current user data from Firebase
                                                                                                                                          const currentUserSnap = await getDoc(doc(db, 'users', currentUserId));
                                                                                                                                              const currentUserData = currentUserSnap.data();
                                                                                                                                                  if (!currentUserData) return;

                                                                                                                                                      const { username, profilePicture } = currentUserData;

                                                                                                                                                          // Check if already following in Firebase
                                                                                                                                                              const existingFollow = await getDoc(
                                                                                                                                                                    doc(db, 'following', currentUserId, 'userFollowing', targetUserId)
                                                                                                                                                                        );
                                                                                                                                                                            if (existingFollow.exists()) return;

                                                                                                                                                                                // ==========================================
                                                                                                                                                                                    // FIREBASE OPERATIONS
                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                            
                                                                                                                                                                                                // Add to following subcollection
                                                                                                                                                                                                    await setDoc(
                                                                                                                                                                                                          doc(db, 'following', currentUserId, 'userFollowing', targetUserId),
                                                                                                                                                                                                                { username, profilePicture, createdAt: serverTimestamp() }
                                                                                                                                                                                                                    );

                                                                                                                                                                                                                        // Add to followers subcollection
                                                                                                                                                                                                                            await setDoc(
                                                                                                                                                                                                                                  doc(db, 'followers', targetUserId, 'userFollowers', currentUserId),
                                                                                                                                                                                                                                        { username, profilePicture, createdAt: serverTimestamp() }
                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                // Update counters
                                                                                                                                                                                                                                                    await updateDoc(doc(db, 'users', currentUserId), {
                                                                                                                                                                                                                                                          followingCount: increment(1),
                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                  await updateDoc(doc(db, 'users', targetUserId), {
                                                                                                                                                                                                                                                                        followersCount: increment(1),
                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                // Create notification
                                                                                                                                                                                                                                                                                    await setDoc(
                                                                                                                                                                                                                                                                                          doc(db, 'notifications', targetUserId, 'userNotifications', currentUserId),
                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                        type: 'follow',
                                                                                                                                                                                                                                                                                                                fromUserId: currentUserId,
                                                                                                                                                                                                                                                                                                                        username,
                                                                                                                                                                                                                                                                                                                                profilePicture,
                                                                                                                                                                                                                                                                                                                                        rankScore: 10,
                                                                                                                                                                                                                                                                                                                                                createdAt: serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                        read: false,
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                      // Get push token from Firebase
                                                                                                                                                                                                                                                                                                                                                                          const targetUserSnap = await getDoc(doc(db, 'users', targetUserId));
                                                                                                                                                                                                                                                                                                                                                                              const targetUserData = targetUserSnap.data();

                                                                                                                                                                                                                                                                                                                                                                                  if (targetUserData?.expoPushToken) {
                                                                                                                                                                                                                                                                                                                                                                                        await sendPushNotification(
                                                                                                                                                                                                                                                                                                                                                                                                targetUserData.expoPushToken,
                                                                                                                                                                                                                                                                                                                                                                                                        'New Follower',
                                                                                                                                                                                                                                                                                                                                                                                                                `${username} started following you`
                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                              // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                  // SUPABASE MIRROR OPERATIONS (Wrapped in try/catch to avoid breaking frontend on failure)
                                                                                                                                                                                                                                                                                                                                                                                                                                      // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                // Mirror Follow Relationship
                                                                                                                                                                                                                                                                                                                                                                                                                                                      await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                              .from('follows')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .insert([{ follower_id: currentUserId, following_id: targetUserId }]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Mirror Counters via RPC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await supabase.rpc('increment_following', { row_id: currentUserId, value: 1 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await supabase.rpc('increment_followers', { row_id: targetUserId, value: 1 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Mirror Notification Record
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('notifications')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .insert([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user_id: targetUserId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      from_user_id: currentUserId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type: 'follow',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rank_score: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          read: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (sbError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('Supabase Mirroring Error during follow:', sbError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Error following user:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * UNFOLLOW USER (Dual Write to Firebase and Supabase)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const unfollowUser = async (currentUserId: string, targetUserId: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // FIREBASE OPERATIONS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await deleteDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc(db, 'following', currentUserId, 'userFollowing', targetUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await deleteDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc(db, 'followers', targetUserId, 'userFollowers', currentUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await updateDoc(doc(db, 'users', currentUserId), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        followingCount: increment(-1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await updateDoc(doc(db, 'users', targetUserId), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      followersCount: increment(-1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await deleteDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc(db, 'notifications', targetUserId, 'userNotifications', currentUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // SUPABASE MIRROR OPERATIONS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Remove follow row
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('follows')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .delete()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .eq('follower_id', currentUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq('following_id', targetUserId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Decrement counters via RPC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await supabase.rpc('increment_following', { row_id: currentUserId, value: -1 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await supabase.rpc('increment_followers', { row_id: targetUserId, value: -1 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Remove notification row
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .from('notifications')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .delete()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eq('user_id', targetUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .eq('from_user_id', currentUserId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eq('type', 'follow');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (sbError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Supabase Mirroring Error during unfollow:', sbError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Error unfollowing user:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                