import { Alert, Linking, Platform } from 'react-native';

export const GlobalPaymentManager = {
  /**
     * Universal Payment Initialization Gateway
        * Dispatches appropriate client UI inputs depending on gateway engine capability.
           */
             initializePayment: async (selectedMethodId: string, postItem: any, amount: number = 500) => {
                 
                     // 1. AFRICA REGIONAL MOBILE MONEY SYSTEM (M-Pesa, Airtel, MTN, Vodafone)
                         // Requires a physical phone number configuration to dispatch an instant STK SIM overlay prompt.
                             if (["mpesa", "airtel", "mobile_money", "mtn_gh", "vodafone_gh"].includes(selectedMethodId)) {
                                   
                                         // Safety web browser fallback loop
                                               if (Platform.OS === 'web') {
                                                       const inputNum = prompt("Enter your Mobile Money Number (including country calling code):", "");
                                                               if (inputNum && inputNum.trim() !== "") {
                                                                         await GlobalPaymentManager.dispatchBackendTransaction("paystack", selectedMethodId, postItem, amount, inputNum.trim());
                                                                                 }
                                                                                         return;
                                                                                               }

                                                                                                     // Native Mobile input form overlay layer
                                                                                                           Alert.prompt(
                                                                                                                   "Mobile Money Processing",
                                                                                                                           "Please enter your payment account phone number to receive the instant payment authorization SIM PIN prompt on your phone.",
                                                                                                                                   [
                                                                                                                                             { text: "Cancel", style: "cancel" },
                                                                                                                                                       {
                                                                                                                                                                   text: "Authorize PIN Prompt",
                                                                                                                                                                               onPress: async (inputPhoneNumber?: string) => {
                                                                                                                                                                                             if (!inputPhoneNumber || inputPhoneNumber.trim() === "") {
                                                                                                                                                                                                             Alert.alert("Input Required", "A valid phone account digits pattern is mandatory.");
                                                                                                                                                                                                                             return;
                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                         await GlobalPaymentManager.dispatchBackendTransaction("paystack", selectedMethodId, postItem, amount, inputPhoneNumber.trim());
                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                       ],
                                                                                                                                                                                                                                                                                               "plain-text"
                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                           return;
                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                   // 🗺️ 2. DYNAMIC WESTERN & ASIAN DIGITAL WALLETS (UPI, Pix, WeChat, GCash, Cards)
                                                                                                                                                                                                                                                                                                                       // No telephone context input needed. We route straight to our global multi-gateway framework engine.
                                                                                                                                                                                                                                                                                                                           const isAfricanGateway = ["bank_transfer", "ussd", "eft", "card"].includes(selectedMethodId) && 
                                                                                                                                                                                                                                                                                                                                                        ["KE", "NG", "GH", "ZA"].includes(postItem.user?.country_code);

                                                                                                                                                                                                                                                                                                                                                            const targetedProvider = isAfricanGateway ? "paystack" : "stripe";
                                                                                                                                                                                                                                                                                                                                                                await GlobalPaymentManager.dispatchBackendTransaction(targetedProvider, selectedMethodId, postItem, amount);
                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                       * 📡 Production API Server Dispatcher
                                                                                                                                                                                                                                                                                                                                                                          * Routes instructions directly to separate backend gateway engines on your Supabase server layer.
                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                               dispatchBackendTransaction: async (provider: "paystack" | "stripe", channelId: string, postItem: any, amount: number, accountPhone?: string) => {
                                                                                                                                                                                                                                                                                                                                                                                   try {
                                                                                                                                                                                                                                                                                                                                                                                         // Direct unified call routing variables context straight to your backend edge processors
                                                                                                                                                                                                                                                                                                                                                                                               const endpoint = "https://jywoururkjaszyfrfqnd.supabase.co";
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                           const response = await fetch(endpoint, {
                                                                                                                                                                                                                                                                                                                                                                                                                   method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                           headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                   body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                             gatewayProvider: provider,   // 🎯 Tells backend whether to execute via Paystack or Stripe APIs
                                                                                                                                                                                                                                                                                                                                                                                                                                                       paymentChannel: channelId,     // Specific item tapped (e.g. 'upi', 'pix', 'wechat', 'mpesa')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 postId: postItem.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           recipientId: postItem.user?.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     amount: amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               phoneNumber: accountPhone || null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const paymentResult = await response.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (paymentResult.success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // A. WALLET DEEP-LINKING OR SECURE CARD PORTALS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (paymentResult.checkoutUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Wakes up PhonePe/GPay for UPI intents, or drops into an Alipay/WeChat authorization deep-link intent!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const canOpenUrl = await Linking.canOpenURL(paymentResult.checkoutUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (canOpenUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await Linking.openURL(paymentResult.checkoutUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Fallback alternative to display a structured web gateway portal fallback
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Alert.alert("Checkout Redirect", "Opening secure transaction validation sheet container in browser viewport.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await Linking.openURL(paymentResult.checkoutUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // B. LOCAL AFRICAN MOBILE MONEY SIM OVERLAYS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   else if (accountPhone) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Alert.alert("SIM Prompt Sent", "An execution signal was delivered to your SIM provider network. Put in your security PIN code to finalize the transfer.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Alert.alert("Gateway Refusal", paymentResult.message || "The merchant clearing networks declined initialization.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   console.error("Critical core dispatcher crash trace:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Alert.alert("Handshake Interrupted", "Could not establish validation connections with global core network transaction clearing nodes.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               