// src/services/notificationService.ts
import * as Notifications from 'expo-notifications';
import * as Device from 'expo-device';
import { Platform } from 'react-native';
import { db } from '../firebaseConfig';
import { supabase } from '../config/supabase'; // Imported your existing Supabase client
import { doc, setDoc, getDoc } from 'firebase/firestore';
import { collection, query, where, onSnapshot } from 'firebase/firestore'; 

/**
 * Async wrapper for sending Expo push notifications
  */
  const sendPushNotification = async (token: string, title: string, body: string) => {
    try {
        await fetch('https://exp.host/--/api/v2/push/send', {
              method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                          body: JSON.stringify({
                                  to: token,
                                          sound: 'default',
                                                  title,
                                                          body,
                                                                }),
                                                                    });
                                                                      } catch (err) {
                                                                          console.error('Error sending push notification:', err);
                                                                            }
                                                                            };

                                                                            /**
                                                                             * Request permission and get Expo push token for a user
                                                                              */
                                                                              export async function registerForPushNotificationsAsync(userId: string) {
                                                                                let token;

                                                                                  if (Device.isDevice) {
                                                                                      const { status: existingStatus } = await Notifications.getPermissionsAsync();
                                                                                          let finalStatus = existingStatus;

                                                                                              if (existingStatus !== 'granted') {
                                                                                                    const { status } = await Notifications.requestPermissionsAsync();
                                                                                                          finalStatus = status;
                                                                                                              }

                                                                                                                  if (finalStatus !== 'granted') {
                                                                                                                        alert('Failed to get push token for notifications!');
                                                                                                                              return;
                                                                                                                                  }

                                                                                                                                      const tokenData = await Notifications.getExpoPushTokenAsync();
                                                                                                                                          token = tokenData.data;

                                                                                                                                              // 1. Save token in Firestore under the user (Original Logic)
                                                                                                                                                  await setDoc(
                                                                                                                                                        doc(db, 'users', userId),
                                                                                                                                                              { expoPushToken: token },
                                                                                                                                                                    { merge: true }
                                                                                                                                                                        );

                                                                                                                                                                            // 2. Save token in Supabase under the users table (Parallel Logic)
                                                                                                                                                                                try {
                                                                                                                                                                                      const { error } = await supabase
                                                                                                                                                                                              .from('users')
                                                                                                                                                                                                      .update({ expo_push_token: token })
                                                                                                                                                                                                              .eq('id', userId);
                                                                                                                                                                                                                      
                                                                                                                                                                                                                            if (error) console.error('Supabase error saving push token:', error.message);
                                                                                                                                                                                                                                } catch (supaErr) {
                                                                                                                                                                                                                                      console.error('Failed to update Supabase push token:', supaErr);
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                alert('Must use a physical device for push notifications!');
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                    return token;
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                     * Send push notification for new follow
                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                      export const sendFollowNotification = async (
                                                                                                                                                                                                                                                        userId: string,
                                                                                                                                                                                                                                                          followerName: string
                                                                                                                                                                                                                                                          ) => {
                                                                                                                                                                                                                                                            let expoPushToken: string | null = null;

                                                                                                                                                                                                                                                              // 1. Fetch token from Firestore (Original Logic)
                                                                                                                                                                                                                                                                const userSnap = await getDoc(doc(db, 'users', userId));
                                                                                                                                                                                                                                                                  const userData = userSnap.data();
                                                                                                                                                                                                                                                                    if (userData?.expoPushToken) {
                                                                                                                                                                                                                                                                        expoPushToken = userData.expoPushToken;
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                            // 2. Fallback: If Firestore failed or is empty, try to resolve via Supabase
                                                                                                                                                                                                                                                                              if (!expoPushToken) {
                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                        const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                .from('users')
                                                                                                                                                                                                                                                                                                        .select('expo_push_token')
                                                                                                                                                                                                                                                                                                                .eq('id', userId)
                                                                                                                                                                                                                                                                                                                        .single();

                                                                                                                                                                                                                                                                                                                              if (data?.expo_push_token && !error) {
                                                                                                                                                                                                                                                                                                                                      expoPushToken = data.expo_push_token;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                } catch (supaErr) {
                                                                                                                                                                                                                                                                                                                                                      console.error('Supabase token fetch error during follow notification:', supaErr);
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                              if (!expoPushToken) return;

                                                                                                                                                                                                                                                                                                                                                                // Use the new async helper
                                                                                                                                                                                                                                                                                                                                                                  await sendPushNotification(
                                                                                                                                                                                                                                                                                                                                                                      expoPushToken,
                                                                                                                                                                                                                                                                                                                                                                          'New Follower',
                                                                                                                                                                                                                                                                                                                                                                              `${followerName} started following you`
                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                export const subscribeToNotifications = (
                                                                                                                                                                                                                                                                                                                                                                                  userId: string,
                                                                                                                                                                                                                                                                                                                                                                                    callback: (notifications: any[]) => void
                                                                                                                                                                                                                                                                                                                                                                                    ) => {
                                                                                                                                                                                                                                                                                                                                                                                      // 1. Listen to Firebase Realtime updates (Original Logic)
                                                                                                                                                                                                                                                                                                                                                                                        const q = query(
                                                                                                                                                                                                                                                                                                                                                                                            collection(db, 'notifications'),
                                                                                                                                                                                                                                                                                                                                                                                                where('userId', '==', userId)
                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                    const unsubscribeFirebase = onSnapshot(q, (snapshot) => {
                                                                                                                                                                                                                                                                                                                                                                                                        const notifications: any[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                            snapshot.forEach((docSnap) => {
                                                                                                                                                                                                                                                                                                                                                                                                                  notifications.push({ id: docSnap.id, ...docSnap.data() });
                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                          callback(notifications);
                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                              // 2. Listen to Supabase Realtime updates (Parallel Logic)
                                                                                                                                                                                                                                                                                                                                                                                                                                const supabaseSubscription = supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                    .channel(`public:notifications:userId=eq.${userId}`)
                                                                                                                                                                                                                                                                                                                                                                                                                                        .on(
                                                                                                                                                                                                                                                                                                                                                                                                                                              'postgres_changes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            event: '*', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    schema: 'public',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            table: 'notifications',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    filter: `user_id=eq.${userId}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Fetch full fresh dataset from Supabase on any change event to sync with UI callback
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .from('notifications')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .select('*')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq('user_id', userId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!error && data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const mappedNotifications = data.map(item => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: item.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        userId: item.user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        callback(mappedNotifications);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .subscribe();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Return a combined unsubscribe cleanup function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unsubscribeFirebase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          supabase.removeChannel(supabaseSubscription);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * Send push notification for new post
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export const sendNewPostNotification = async (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userId: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let expoPushToken: string | null = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // 1. Fetch token from Firestore (Original Logic)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const userSnap = await getDoc(doc(db, 'users', userId));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const userData = userSnap.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (userData?.expoPushToken) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expoPushToken = userData.expoPushToken;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 2. Fallback: If Firestore failed or is empty, try to resolve via Supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!expoPushToken) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .select('expo_push_token')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq('id', userId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (data?.expo_push_token && !error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expoPushToken = data.expo_push_token;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (supaErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Supabase token fetch error during post notification:', supaErr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!expoPushToken) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Use the new async helper
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await sendPushNotification(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expoPushToken,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'New Post',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        