// src/services/postService.ts
import { db } from '../firebaseConfig';
import {
  collection,
    addDoc,
      serverTimestamp,
        onSnapshot,
          query,
            orderBy,
              doc,
                updateDoc,
                  increment,
                    arrayUnion,
                      getDoc,
                        limit,
                          where,
                          } from 'firebase/firestore';
                          import { uploadPostMedia } from './mediaService';
                          import * as FileSystem from 'expo-file-system';

                          import { checkModeration, checkImageModeration } from './moderationService';
                          
                          import { supabase } from '../config/supabase'; 

                          /**
                           * Create a new post with optional media (image/video)
                            */
                            export const createPost = async (
                                                            userId: string,
                                                                                            content: string,
                                                                                                                              mediaUrlInput: string | null,
                                                                                                                                                                  userCountry: string,
                                                                                                                                                                                                        categoryText?: string
                                                                                                                                                                                                                                              ) => {

                            

                                        // =============================
                                          // AI Text Moderation
                                            // =============================
                                              const textResult = await checkModeration(content);
                                                if (!textResult.allowed) {
                                                    alert(textResult.reason);
                                                        return;
                                                          }

                           let mediaUrl: string | null = mediaUrlInput;
                           let mediaType: 'image' | 'video' | null = null;


                                                            

                                                                // =============================
                                                                  // AI Image Moderation
                                                                    // =============================
                                                                                                                                  // =============================
                                                                                                                                                                                                    // AI Image Moderation
                                                                                                                                                                                                                                                                        // =============================
                                                                                                                                                                                                                                                                                                                                         mediaUrl = mediaUrlInput;
                                                                                                                                                                                                                                                                                                                                                                                                       

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (mediaUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Safely figure out if it's a video or image based on the upload folder string path name structure
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             mediaType = mediaUrl?.includes('videos') || mediaUrl?.toLowerCase().endsWith('.mp4') ? 'video' : 'image';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('Media file path validated successfully:', mediaUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('Media evaluation fallback issue:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert('Failed to check image content');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                    
                                                                                    
                                                                                          
                                                                                          
                                                                                
                                                                                              
                                                                                                      
                                                                                                            
                                                                                                            
                                                                                                                      

                                                                                                                                                
                                                                                                                                                      

                                                                                                                                                        // =============================
                                                                                                                                                          // WRITE TO FIREBASE
                                                                                                                                                            // =============================
                                                                                                                                                              await addDoc(collection(db, 'posts'), {
                                                                                                                                                                                                                                      userId,
                                                                                                                                                                                                                                                                                                            title: categoryText || "General", // Saves category info as the title string
                                                                                                                                                                                                                                                                                                                                                                                  content,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        mediaUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mediaType,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    likesCount: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          commentsCount: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                country: userCountry,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      createdAt: serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                              
                                                                                                                                                          
                                                                                                                                                                
                                                                                                                                                                        
                                                                                                                                                                      
                                                                                                                                                                          
                                                                                                                                                                              
                                                                                                                                                                                          
                                                                                                                                                                                          
                                                                                                                                                                                        

                                                                                                                                                                                                      // =============================
                                                                                                                                                                                                        // WRITE TO SUPABASE (NEW)
                                                                                                                                                                                                          // =============================
                                                                                                                                                                                                            try {
                                                                                                                                                                                                                const { error } = await supabase
                                                                                                                                                                                                                      .from('posts')
                                                                                                                                                                                                                            .insert([
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                   user_id: userId,
                                                                                                                                                                                                                                   title: categoryText || "General",
                                                                                                                                                                                                                                   content: content,
                                                                                                                                                                                                                                   media_url: mediaUrl,
                                                                                                                                                                                                                                    media_type: mediaType,
                                                                                                                                                                                                                                    likes_count: 0,
                                                                                                                                                                                                                                   comments_count: 0,
                                                                                                                                                                                                                                  country: userCountry,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                  ]);

                                                                                                                                                                                                                                                                                                                                      if (error) {
                                                                                                                                                                                                                                                                                                                                            console.error('Error saving post to Supabase:', error.message);
                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                      console.log('Successfully synchronized post to Supabase!');
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                            } catch (supabaseErr) {
                                                                                                                                                                                                                                                                                                                                                                console.error('Supabase execution error:', supabaseErr);
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                                                                   * Helper: Compute hours since a post was created
                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                    const hoursSincePosted = (timestamp: any) => {
                                                                                                                                                                                                                                                                                                                                                                      if (!timestamp) return 0;
                                                                                                                                                                                                                                                                                                                                                                        const now = new Date().getTime();
                                                                                                                                                                                                                                                                                                                                                                          const created = timestamp.toDate
                                                                                                                                                                                                                                                                                                                                                                              ? timestamp.toDate().getTime()
                                                                                                                                                                                                                                                                                                                                                                                  : new Date(timestamp).getTime();
                                                                                                                                                                                                                                                                                                                                                                                    return (now - created) / (1000 * 60 * 60); // milliseconds -> hours
                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                     * Subscribe to country trending posts with weighted score
                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                      export const subscribeToCountryTrending = (
                                                                                                                                                                                                                                                                                                                                                                                        country: string,
                                                                                                                                                                                                                                                                                                                                                                                          callback: any,
                                                                                                                                                                                                                                                                                                                                                                                            limitCount = 10
                                                                                                                                                                                                                                                                                                                                                                                            ) => {
                                                                                                                                                                                                                                                                                                                                                                                              const q = query(
                                                                                                                                                                                                                                                                                                                                                                                                  collection(db, 'posts'),
                                                                                                                                                                                                                                                                                                                                                                                                      where('country', '==', country),
                                                                                                                                                                                                                                                                                                                                                                                                          limit(limitCount)
                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                              return onSnapshot(q, (snapshot) => {
                                                                                                                                                                                                                                                                                                                                                                                                                  const posts: any[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                      snapshot.forEach((doc) => {
                                                                                                                                                                                                                                                                                                                                                                                                                            const data = doc.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                  const likes = data.likesCount || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                        const comments = data.commentsCount || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                              const hours = hoursSincePosted(data.createdAt);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const score = (likes * 2) + (comments * 3) - hours;

                                                                                                                                                                                                                                                                                                                                                                                                                                                          posts.push({ id: doc.id, ...data, score });
                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  callback(posts);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * Subscribe to global trending posts with weighted score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export const subscribeToGlobalTrending = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        callback: any,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          limitCount = 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const q = query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                collection(db, 'posts'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    limit(limitCount)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return onSnapshot(q, (snapshot) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const posts: any[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                snapshot.forEach((doc) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const data = doc.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const likes = data.likesCount || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const comments = data.commentsCount || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const hours = hoursSincePosted(data.createdAt);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const score = (likes * 2) + (comments * 3) - hours;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    posts.push({ id: doc.id, ...data, score });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Sort descending by weighted score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                posts.sort((a, b) => (b.score || 0) - (a.score || 0));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    callback(posts);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * Subscribe to all posts ordered by creation time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export const subscribeToPosts = (callback: (posts: any[]) => void) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const q = query(collection(db, 'posts'), orderBy('createdAt', 'desc'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return onSnapshot(q, (snapshot) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const posts: any[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        snapshot.forEach((docSnap) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              posts.push({ id: docSnap.id, ...docSnap.data() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      callback(posts);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Subscribe to live changes for a single post (likes/comments)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export const subscribeToPostUpdates = (postId: string, callback: (post: any) => void) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const docRef = doc(db, 'posts', postId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return onSnapshot(docRef, (docSnap) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (docSnap.exists()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback({ id: docSnap.id, ...docSnap.data() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  