const PAYSTACK_SECRET_KEY = Deno.env.get("PAYSTACK_SECRET_KEY") ?? "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      };

      Deno.serve(async (req) => {
        if (req.method === "OPTIONS") {
            return new Response("ok", { headers: corsHeaders });
              }

                try {
                    const { gatewayProvider, paymentChannel, postId, recipientId, amount, phoneNumber } = await req.json();

                        // Verify request is targeting Paystack
                            if (gatewayProvider !== "paystack") {
                                  throw new Error("Unsupported gateway merchant provider requested. Only 'paystack' is supported.");
                                      }

                                          // ==========================================
                                              // ROUTE A: DIRECT MOBILE MONEY CHARGE
                                                  // ==========================================
                                                      if (phoneNumber) {
                                                            const paystackPayload = {
                                                                    email: `donor_${Date.now()}@yourdomain.com`,
                                                                            amount: amount * 100, // Paystack charges in minor units (cents)
                                                                                    currency: "KES",
                                                                                            mobile_money: {
                                                                                                      phone: phoneNumber,
                                                                                                                provider: paymentChannel // e.g. "mpesa"
                                                                                                                        },
                                                                                                                                metadata: {
                                                                                                                                          postId: postId || "",
                                                                                                                                                    recipientId: recipientId || ""
                                                                                                                                                            }
                                                                                                                                                                  };

                                                                                                                                                                        // FIXED: Pointing to Paystack's official direct charge endpoint
                                                                                                                                                                              const response = await fetch("https://paystack.co", {
                                                                                                                                                                                      method: "POST",
                                                                                                                                                                                              headers: {
                                                                                                                                                                                                        "Authorization": `Bearer ${PAYSTACK_SECRET_KEY}`,
                                                                                                                                                                                                                  "Content-Type": "application/json"
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                  body: JSON.stringify(paystackPayload)
                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                              const data = await response.json();
                                                                                                                                                                                                                                                    return new Response(JSON.stringify({ success: data.status, data }), {
                                                                                                                                                                                                                                                            headers: { ...corsHeaders, "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                          // ==========================================
                                                                                                                                                                                                                                                                              // ROUTE B: WEB CHECKOUT LINK (CARDS & WORLDWIDE)
                                                                                                                                                                                                                                                                                  // ==========================================
                                                                                                                                                                                                                                                                                      const paystackCheckoutPayload = {
                                                                                                                                                                                                                                                                                            email: `donor_${Date.now()}@yourdomain.com`,
                                                                                                                                                                                                                                                                                                  amount: amount * 100,
                                                                                                                                                                                                                                                                                                        currency: "KES",
                                                                                                                                                                                                                                                                                                              channels: paymentChannel ? [paymentChannel] : ["card", "mobile_money"],
                                                                                                                                                                                                                                                                                                                    metadata: {
                                                                                                                                                                                                                                                                                                                            postId: postId || "",
                                                                                                                                                                                                                                                                                                                                    recipientId: recipientId || ""
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                  // FIXED: Pointing to Paystack's official transaction initialize endpoint
                                                                                                                                                                                                                                                                                                                                                      const response = await fetch("https://paystack.co", {
                                                                                                                                                                                                                                                                                                                                                            method: "POST",
                                                                                                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                                                                                                          "Authorization": `Bearer ${PAYSTACK_SECRET_KEY}`,
                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify(paystackCheckoutPayload)
                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                      const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                                          return new Response(JSON.stringify({ 
                                                                                                                                                                                                                                                                                                                                                                                                                success: data.status, 
                                                                                                                                                                                                                                                                                                                                                                                                                      checkoutUrl: data.data?.authorization_url || null 
                                                                                                                                                                                                                                                                                                                                                                                                                          }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { ...corsHeaders, "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          return new Response(JSON.stringify({ success: false, message: error.message }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                status: 400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: { ...corsHeaders, "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
