// src/screens/LiveStreamsFeed.tsx
import React, { useEffect, useState } from 'react';
import { View, Text, FlatList, Dimensions, TouchableOpacity, ActivityIndicator, StyleSheet } from 'react-native';
import { useNavigation, NavigationProp } from "expo-router/react-navigation";
import { getDatabase, ref, onValue } from 'firebase/database';
import {supabase} from '../config/supabase';
const { height } = Dimensions.get('window');

// Emoji map for categories
const CATEGORY_EMOJI: Record<string, string> = {
  "Political/Governance": "🔴",
    Sports: "🟠",
      Health: "🟢",
        "Educational/Philosophical": "🔵",
          Entertainment: "🌸",
            Technological: "🟣",
              Religious: "🕊️",
                "Development/Economics": "🟤",
                  "Personal/Warm Touch": "💛",
                    "Public Information": "🔷",
                    "Sociocultural": "🎭",
                    "Breaking News": "📰",
                    "Love": "❤️",
                      Other: "⚪",
                        Gaming: "🎮",
                        };

                        // Stream type definition
                        type Stream = {
                          id: string;
                            title: string;
                              category: string;
                                viewers: number;
                                  isLive: boolean;
                                  };

                                  // Define your app's stack navigation parameter structure
                                  type RootStackParamList = {
                                    LiveStreamsFeed: undefined;
                                      LiveViewer: { streamId: string };
                                      };

                                      export default function LiveStreamsFeed() {
                                        // Pass the type definitions into useNavigation
                                          const navigation = useNavigation<NavigationProp<RootStackParamList>>();
                                            
                                              // Re-added the state variables to resolve the errors
                                                const [streams, setStreams] = useState<Stream[]>([]);
                                                  const [loading, setLoading] = useState<boolean>(true);

                                                    // Fetch live streams from Firebase
                                                      useEffect(() => {
                                                          const database = getDatabase();
                                                              const streamsRef = ref(database, 'liveStreams'); // Path in Firebase
                                                                  
                                                                      const unsubscribe = onValue(streamsRef, snapshot => {
                                                                            const data = snapshot.val() || {};
                                                                                  const parsedStreams: Stream[] = Object.keys(data).map(key => ({
                                                                                          id: key,
                                                                                                  title: data[key].title,
                                                                                                          category: data[key].category || 'Other',
                                                                                                                  viewers: data[key].viewers || 0, // viewer count in Firebase
                                                                                                                          isLive: data[key].isLive || false, // live status in Firebase
                                                                                                                                }));
                                                                                                                                      setStreams(parsedStreams);
                                                                                                                                            setLoading(false);
                                                                                                                                                });

                                                                                                                                                    return () => unsubscribe();
                                                                                                                                                      }, []);

                                                                                                                                                        const renderItem = ({ item }: { item: Stream }) => {
                                                                                                                                                            const emoji = CATEGORY_EMOJI[item.category] || '⚪';
                                                                                                                                                                return (
                                                                                                                                                                      <TouchableOpacity
                                                                                                                                                                              style={styles.streamContainer}
                                                                                                                                                                                      onPress={() => navigation.navigate("LiveViewer", { streamId: item.id })}
                                                                                                                                                                                            >
                                                                                                                                                                                                    {/* Live Status and Viewers */}
                                                                                                                                                                                                            <View style={styles.statusContainer}>
                                                                                                                                                                                                                      <View style={[styles.liveDot, { backgroundColor: item.isLive ? 'red' : 'grey' }]} />
                                                                                                                                                                                                                                <Text style={styles.viewerText}>{item.viewers} viewers</Text>
                                                                                                                                                                                                                                        </View>

                                                                                                                                                                                                                                                {/* Stream Title with Category Emoji */}
                                                                                                                                                                                                                                                        <Text style={styles.title}>
                                                                                                                                                                                                                                                                  {emoji} {item.title}
                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                </TouchableOpacity>
                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                        if (loading) {
                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                  <View style={styles.loadingContainer}>
                                                                                                                                                                                                                                                                                                          <ActivityIndicator size="large" color="#007AFF" />
                                                                                                                                                                                                                                                                                                                  <Text style={{ color: '#fff', marginTop: 10 }}>Loading live streams...</Text>
                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <FlatList
                                                                                                                                                                                                                                                                                                                                          data={streams}
                                                                                                                                                                                                                                                                                                                                                renderItem={renderItem}
                                                                                                                                                                                                                                                                                                                                                      pagingEnabled
                                                                                                                                                                                                                                                                                                                                                            showsVerticalScrollIndicator={false}
                                                                                                                                                                                                                                                                                                                                                                  keyExtractor={item => item.id}
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                          streamContainer: {
                                                                                                                                                                                                                                                                                                                                                                              height: height,
                                                                                                                                                                                                                                                                                                                                                                                  justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#000',
                                                                                                                                                                                                                                                                                                                                                                                              paddingHorizontal: 20,
                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                  statusContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                      position: 'absolute',
                                                                                                                                                                                                                                                                                                                                                                                                          top: 50,
                                                                                                                                                                                                                                                                                                                                                                                                              left: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                  flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                          liveDot: {
                                                                                                                                                                                                                                                                                                                                                                                                                              width: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                          marginRight: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                              viewerText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: '500',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loadingContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#000',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    