


Deno.serve(async (req) => {


  // CORS Preflight Header Validation Handler
    if (req.method === 'OPTIONS') {
        return new Response('ok', {
              headers: {
                      'Access-Control-Allow-Origin': '*',
                              'Access-Control-Allow-Methods': 'POST, GET',
                                      'Access-Control-Allow-Headers': 'authorization, x-client-info, apiKey, content-type',
                                            }
                                                });
                                                  }

                                                    const url = new URL(req.url);
                                                      const secretKey = Deno.env.get("sk_test_71d528e87a5e451e747d8a65644293bfec9079fd") || "";

                                                        // --- SUB-ROUTE 1: FETCH DYNAMIC LOCAL PAYMENT METHODS ---
                                                          if (url.pathname.endsWith('/payment-methods')) {
                                                              try {
                                                                    // Auto-sense user country from cloudflare location headers, default to US if unavailable
                                                                          const countryCode = url.searchParams.get("country") || req.headers.get("cf-ipcountry") || "US";

                                                                                // Setup dynamic fallback UI configurations based on sensed global regions
                                                                                      let uiMethods = [];

                                                                                            if (countryCode.toUpperCase() === "KE") {
                                                                                                    uiMethods = [
                                                                                                              { id: "mpesa", name: "M-Pesa Mobile Money" },
                                                                                                                        { id: "card", name: "International Credit/Debit Card" }
                                                                                                                                ];
                                                                                                                                      } else if (["US", "GB", "CA", "EU"].includes(countryCode.toUpperCase())) {
                                                                                                                                              uiMethods = [
                                                                                                                                                        { id: "card", name: "Credit / Debit Card" },
                                                                                                                                                                  { id: "applepay", name: "Apple Pay / Google Pay" }
                                                                                                                                                                          ];
                                                                                                                                                                                } else {
                                                                                                                                                                                        // Universal global defaults
                                                                                                                                                                                                uiMethods = [
                                                                                                                                                                                                          { id: "card", name: "Global Bank Card" }
                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                              return new Response(JSON.stringify({ success: true, country: countryCode, methods: uiMethods }), {
                                                                                                                                                                                                                                      headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" }
                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                } catch (err: any) {
                                                                                                                                                                                                                                                      return new Response(JSON.stringify({ error: err.message }), { 
                                                                                                                                                                                                                                                              status: 500, 
                                                                                                                                                                                                                                                                      headers: { "Access-Control-Allow-Origin": "*" } 
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    // --- SUB-ROUTE 2: PROCESS THE DEPOSIT / DONATION TRANSACTION ---
                                                                                                                                                                                                                                                                                      if (url.pathname.endsWith('/process-payment') || req.method === 'POST') {
                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                const { amount, currency, streamerId, method, email } = await req.json();
                                                                                                                                                                                                                                                                                                      const cleanMethod = String(method).toLowerCase();

                                                                                                                                                                                                                                                                                                            // Keep direct integrations for specific legacy system routes if necessary
                                                                                                                                                                                                                                                                                                                  if (method === 'PayPal') {
                                                                                                                                                                                                                                                                                                                          return new Response(JSON.stringify({
                                                                                                                                                                                                                                                                                                                                    success: true,
                                                                                                                                                                                                                                                                                                                                              gateway: "PayPal_Redirect",
                                                                                                                                                                                                                                                                                                                                                        redirectUrl: `https://paypal.com${amount}`
                                                                                                                                                                                                                                                                                                                                                                }), { headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } });
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                            if (method === 'Daraja') {
                                                                                                                                                                                                                                                                                                                                                                                    return new Response(JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                              success: true,
                                                                                                                                                                                                                                                                                                                                                                                                        gateway: "Daraja_STKPush_Active",
                                                                                                                                                                                                                                                                                                                                                                                                                  message: "Forwarding processing payload straight down internal Safaricom nodes."
                                                                                                                                                                                                                                                                                                                                                                                    }), { headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } });
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                // --- PAYSTACK ENGINE CORE TRANSACTION ROUTER ---
                                                                                                                                                                                                                                                                                                                                                                                                      // Paystack converts standard amounts into minor currency parameters (e.g., cents or shillings)
                                                                                                                                                                                                                                                                                                                                                                                                            const amountInMinorUnits = Math.round(amount * 100);

                                                                                                                                                                                                                                                                                                                                                                                                                  const paystackIntentRes = await fetch("https://paystack.co", {
                                                                                                                                                                                                                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                            "Authorization": `Bearer ${secretKey}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                email: email || "payment@realdapp.com", // Fallback system registration parameter if user email is missing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          amount: amountInMinorUnits,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currency: currency?.toUpperCase() || "USD",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              callback_url: "https://reald-app.com", // Auto-returns users safely to your Feed Screen file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    streamerId: streamerId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                billingChannel: method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            custom_fields: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { display_name: "Billing Method", variable_name: "billing_method", value: cleanMethod }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const paystackData = await paystackIntentRes.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!paystackIntentRes.ok || !paystackData.status) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error(paystackData.message || "Failed to initialize Paystack gateway node.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              gateway: "Paystack",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checkoutUrl: paystackData.data.authorization_url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              referenceId: paystackData.data.reference
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }), { headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(JSON.stringify({ error: err.message }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: { "Access-Control-Allow-Origin": "*" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "Endpoint route not found." }), { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: 404, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: { "Access-Control-Allow-Origin": "*" } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
